### ISSUE TITLE
How to use in WPF

### ISSUE THREAD

**Issue by zcyc** [Sekoree/YALibMPV#1]

**Comment by Sekoree** [comment]
I've added an Avalonia and a WPF sample, however I don't know much about embedding stuff in WPF which is why its broken(?)
The WPF sample is loosely based on the LibVLC WPF control, it worked once before, then I removed something that isn't getting generated anymore and now it stopped calling the `OnApplyTemplate` method.
The Avalonia sample works though.

Samples are here
https://github.com/Sekoree/YALibMPV/tree/master/samples

**Comment by zcyc** [comment]
Thank you.
